{"student_academic": {"grade_size": null, "student_id": "47b9e371-b0fd-48cd-81e0-26a3cdf5c2e3", "rank_number": null,
                      "school_city": null, "school_name": null, "total_students": null, "rank_percentile": null,
                      "rank_scope_code": null, "school_code_val": null, "school_type_code": null,
                      "school_type_notes": null, "rank_evidence_notes": null, "student_academic_id": null,
                      "other_curriculum_notes": null, "rank_evidence_level_code": null,
                      "curriculum_combination_notes": null},
 "student_language": {"notes": null, "student_id": "47b9e371-b0fd-48cd-81e0-26a3cdf5c2e3", "best_test_date": null,
                      "best_test_type_code": null, "student_language_id": null, "use_best_single_test": null,
                      "best_score_status_code": null, "overall_cefr_level_code": null,
                      "language_index_method_notes": null, "prefer_scored_over_estimated": null,
                      "best_language_ability_index_100": null},
 "student_activities": {"student_id": "47b9e371-b0fd-48cd-81e0-26a3cdf5c2e3", "prefer_long_term": null,
                        "quality_rules_notes": null, "impact_required_field": null, "prefer_leadership_roles": null},
 "student_basic_info": {"student_id": "47b9e371-b0fd-48cd-81e0-26a3cdf5c2e3", "MAJ_CODE_VAL": null,
                        "profile_type": null, "CTRY_CODE_VAL": "UK", "current_grade": null, "schema_version": null,
                        "graduation_year": null, "target_entry_term": null, "curriculum_system_notes": null},
 "student_competitions": {"student_id": "47b9e371-b0fd-48cd-81e0-26a3cdf5c2e3", "t1_examples_text": null,
                          "t2_examples_text": null, "t3_examples_text": null, "t4_examples_text": null,
                          "tier_reference_notes": null}, "student_language_det": [], "student_language_pte": [],
 "student_language_ielts": [
     {"notes": null, "test_date": null, "student_id": "47b9e371-b0fd-48cd-81e0-26a3cdf5c2e3", "status_code": null,
      "is_best_score": null, "overall_score": 6.0, "reading_score": null, "writing_score": null, "speaking_score": null,
      "estimated_total": null, "listening_score": null, "evidence_level_code": null, "normalized_index_100": null}],
 "student_language_other": [], "student_project_entries": [], "student_project_outputs": [],
 "student_activity_entries": [{"notes": null, "team_size": null, "events_run": null, "sort_order": null,
                               "student_id": "47b9e371-b0fd-48cd-81e0-26a3cdf5c2e3", "funds_raised": null,
                               "weekly_hours": null, "activity_name": "班级信息委员", "activity_role": "MEMBER",
                               "evidence_type": null, "people_reached": null, "awards_or_media": null,
                               "duration_months": null, "activity_category": "LEADERSHIP",
                               "evidence_link_or_note": null}], "student_academic_ap_course": [],
 "student_language_cambridge": [], "student_language_toefl_ibt": [],
 "student_standardized_tests": {"notes": null, "student_id": "47b9e371-b0fd-48cd-81e0-26a3cdf5c2e3", "is_applicable": 0,
                                "best_test_date": null, "best_test_type": null, "best_total_score": null,
                                "not_applicable_reason": null, "student_standardized_test_id": null},
 "student_academic_ap_profile": {"notes": null, "ap_count": null, "gpa_scale": null, "school_gpa": null,
                                 "student_id": "47b9e371-b0fd-48cd-81e0-26a3cdf5c2e3", "is_weighted": null,
                                 "honors_count": null, "class_rank_available": null, "best_n_ap_for_scoring": null,
                                 "max_ap_offered_by_school": null},
 "student_academic_ib_profile": {"notes": null, "student_id": "47b9e371-b0fd-48cd-81e0-26a3cdf5c2e3",
                                 "ee_grade_code": null, "tok_grade_code": null, "ib_total_predicted": null,
                                 "hl_weight_multiplier": null, "best_n_subjects_for_scoring": null},
 "student_academic_ib_subject": [], "student_competition_entries": [
    {"notes": null, "percentile": null, "rank_value": 1, "sort_order": null,
     "student_id": "47b9e371-b0fd-48cd-81e0-26a3cdf5c2e3", "result_text": "第一", "evidence_type": null,
     "competition_name": "数学竞赛", "competition_tier": null, "competition_year": null, "competition_field": "MATH",
     "competition_level": "SCHOOL", "participants_count": null, "evidence_link_or_note": null}],
 "student_projects_experience": {"student_id": "47b9e371-b0fd-48cd-81e0-26a3cdf5c2e3", "output_preferred": null,
                                 "strictness_rules_notes": null, "internal_only_output_penalty": null},
 "student_language_languagecert": [],
 "student_academic_a_level_profile": {"notes": null, "student_id": "47b9e371-b0fd-48cd-81e0-26a3cdf5c2e3",
                                      "include_further_math_bonus": null, "best_n_subjects_for_scoring": null},
 "student_academic_a_level_subject": [], "student_language_toefl_essentials": [],
 "student_standardized_test_records": [], "student_basic_info_curriculum_system": [
    {"notes": null, "is_primary": null, "student_id": "47b9e371-b0fd-48cd-81e0-26a3cdf5c2e3",
     "curriculum_system_code": null}],
 "student_academic_chinese_high_school_profile": {"gpa": null, "notes": null, "gpa_scale": null,
                                                  "student_id": "47b9e371-b0fd-48cd-81e0-26a3cdf5c2e3",
                                                  "average_score_100": null, "grading_system_code": null,
                                                  "best_subjects_for_scoring_rule": null},
 "student_academic_chinese_high_school_subject": [
     {"notes": "语文", "score_100": 70, "student_id": "47b9e371-b0fd-48cd-81e0-26a3cdf5c2e3", "chs_subject_id": null},
     {"notes": "数学", "score_100": 80, "student_id": "47b9e371-b0fd-48cd-81e0-26a3cdf5c2e3", "chs_subject_id": null},
     {"notes": "英语", "score_100": 60, "student_id": "47b9e371-b0fd-48cd-81e0-26a3cdf5c2e3", "chs_subject_id": null}]}
