package com.earthseaedu.backend.service;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * BusinessProfileFormMetadata 服务支撑类，提供当前业务模块使用的静态元数据或工具能力。
 */
public final class BusinessProfileFormMetadata {

    public static final Map<String, String> TABLE_LABELS = Map.ofEntries(
        Map.entry("student_basic_info", "学生基本信息"),
        Map.entry("student_basic_info_curriculum_system", "课程体系"),
        Map.entry("student_academic", "学术信息"),
        Map.entry("student_academic_us_high_school_profile", "美高配置"),
        Map.entry("student_academic_us_high_school_course", "美高逐门课成绩"),
        Map.entry("student_academic_other_curriculum_profile", "其他课程体系配置"),
        Map.entry("student_academic_a_level_profile", "A-Level 配置"),
        Map.entry("student_academic_a_level_subject", "A-Level 科目成绩"),
        Map.entry("student_academic_ap_profile", "AP 配置"),
        Map.entry("student_academic_ap_course", "AP 课程成绩"),
        Map.entry("student_academic_ib_profile", "IB 配置"),
        Map.entry("student_academic_ib_subject", "IB 科目成绩"),
        Map.entry("student_academic_chinese_high_school_profile", "普高配置"),
        Map.entry("student_academic_chinese_high_school_subject", "普高科目成绩"),
        Map.entry("student_language_ielts", "雅思"),
        Map.entry("student_language_toefl_ibt", "托福 iBT"),
        Map.entry("student_language_toefl_essentials", "托福 Essentials"),
        Map.entry("student_language_det", "多邻国"),
        Map.entry("student_language_pte", "PTE"),
        Map.entry("student_language_languagecert", "LanguageCert"),
        Map.entry("student_language_cambridge", "剑桥英语"),
        Map.entry("student_language_other", "其他语言考试"),
        Map.entry("student_standardized_test_records", "标化考试"),
        Map.entry("student_competition_entries", "竞赛"),
        Map.entry("student_activity_entries", "活动"),
        Map.entry("student_project_entries", "项目")
    );

    public static final Map<String, String> FIELD_LABELS = Map.ofEntries(
        Map.entry("MAJ_INTEREST_TEXT", "目标专业原始文本"),
        Map.entry("student_id", "学生 ID"),
        Map.entry("schema_version", "架构版本"),
        Map.entry("profile_type", "档案类型"),
        Map.entry("current_grade", "当前年级"),
        Map.entry("graduation_year", "毕业年份"),
        Map.entry("target_entry_term", "目标入学季"),
        Map.entry("CTRY_CODE_VAL", "目标国家"),
        Map.entry("MAJ_CODE_VAL", "目标专业"),
        Map.entry("curriculum_system_notes", "课程体系补充说明"),
        Map.entry("curriculum_system_code", "课程体系"),
        Map.entry("is_primary", "是否主课程体系"),
        Map.entry("student_academic_id", "学术主表 ID"),
        Map.entry("school_name", "学校名称"),
        Map.entry("school_city", "所在城市"),
        Map.entry("school_type_code", "学校类型"),
        Map.entry("school_type_notes", "学校类型补充说明"),
        Map.entry("grade_size", "年级人数"),
        Map.entry("total_students", "学校总人数"),
        Map.entry("rank_number", "排名名次"),
        Map.entry("rank_percentile", "排名百分位"),
        Map.entry("rank_scope_code", "排名范围"),
        Map.entry("rank_evidence_level_code", "排名证据等级"),
        Map.entry("rank_evidence_notes", "排名证据说明"),
        Map.entry("other_curriculum_notes", "其他课程体系说明"),
        Map.entry("curriculum_combination_notes", "混合课程体系说明"),
        Map.entry("curriculum_scope_code", "课程体系范围"),
        Map.entry("best_n_subjects_for_scoring", "用于评分的最佳科目数"),
        Map.entry("include_further_math_bonus", "是否计入高数加分"),
        Map.entry("al_subject_id", "A-Level 科目"),
        Map.entry("stage_code", "阶段"),
        Map.entry("grade_code", "成绩等级"),
        Map.entry("is_predicted", "是否预估"),
        Map.entry("board_code", "考试局"),
        Map.entry("session_code", "考试场次"),
        Map.entry("exam_series", "考试批次"),
        Map.entry("school_gpa", "校内 GPA"),
        Map.entry("gpa_scale", "GPA 满分"),
        Map.entry("is_weighted", "是否加权"),
        Map.entry("class_rank_available", "是否有班级排名"),
        Map.entry("honors_count", "荣誉课程数量"),
        Map.entry("ap_count", "AP 数量"),
        Map.entry("max_ap_offered_by_school", "学校提供 AP 最大数量"),
        Map.entry("best_n_ap_for_scoring", "用于评分的最佳 AP 门数"),
        Map.entry("course_load_rigor_notes", "课程强度说明"),
        Map.entry("student_us_high_school_course_record_id", "美高课程记录 ID"),
        Map.entry("school_year_label", "学年/年级标签"),
        Map.entry("term_code", "学期"),
        Map.entry("us_high_school_course_id", "美高课程"),
        Map.entry("course_name_text", "课程名称"),
        Map.entry("course_category_code", "课程类别"),
        Map.entry("course_level_code", "课程级别"),
        Map.entry("grade_letter_code", "字母成绩"),
        Map.entry("grade_percent", "百分制成绩"),
        Map.entry("credit_earned", "学分"),
        Map.entry("ap_course_id", "AP 课程"),
        Map.entry("score", "分数"),
        Map.entry("year_taken", "考试年份"),
        Map.entry("ib_total_predicted", "IB 总预估分"),
        Map.entry("tok_grade_code", "TOK 等级"),
        Map.entry("ee_grade_code", "EE 等级"),
        Map.entry("hl_weight_multiplier", "HL 加权系数"),
        Map.entry("ib_subject_id", "IB 科目"),
        Map.entry("level_code", "级别"),
        Map.entry("grading_system_code", "评分体系"),
        Map.entry("average_score_100", "百分制平均分"),
        Map.entry("gpa", "GPA"),
        Map.entry("best_subjects_for_scoring_rule", "最佳科目评分规则"),
        Map.entry("chs_subject_id", "普高科目"),
        Map.entry("score_100", "百分制分数"),
        Map.entry("student_language_id", "语言主表 ID"),
        Map.entry("best_test_type_code", "最佳语言考试类型"),
        Map.entry("best_score_status_code", "最佳成绩状态"),
        Map.entry("best_test_date", "最佳考试日期"),
        Map.entry("best_language_ability_index_100", "语言能力指数"),
        Map.entry("overall_cefr_level_code", "综合 CEFR 等级"),
        Map.entry("use_best_single_test", "是否使用最佳单次成绩"),
        Map.entry("prefer_scored_over_estimated", "是否优先已出分"),
        Map.entry("language_index_method_notes", "语言指数说明"),
        Map.entry("status_code", "成绩状态"),
        Map.entry("test_date", "考试日期"),
        Map.entry("overall_score", "总分"),
        Map.entry("reading_score", "阅读分"),
        Map.entry("listening_score", "听力分"),
        Map.entry("speaking_score", "口语分"),
        Map.entry("writing_score", "写作分"),
        Map.entry("estimated_total", "预估总分"),
        Map.entry("evidence_level_code", "证据等级"),
        Map.entry("normalized_index_100", "标准化指数"),
        Map.entry("is_best_score", "是否最佳成绩"),
        Map.entry("total_score", "总分"),
        Map.entry("core_score_1_12", "核心总分"),
        Map.entry("literacy_1_12", "读写能力分"),
        Map.entry("conversation_1_12", "交流能力分"),
        Map.entry("comprehension_1_12", "理解能力分"),
        Map.entry("literacy_score", "Literacy 分"),
        Map.entry("comprehension_score", "Comprehension 分"),
        Map.entry("conversation_score", "Conversation 分"),
        Map.entry("production_score", "Production 分"),
        Map.entry("exam_name", "考试名称"),
        Map.entry("cefr_level_code", "CEFR 等级"),
        Map.entry("use_of_english_score", "Use of English 分"),
        Map.entry("test_name", "考试名称"),
        Map.entry("score_total", "总分"),
        Map.entry("band_or_scale_desc", "分制说明"),
        Map.entry("score_breakdown_json", "分项成绩 JSON"),
        Map.entry("student_standardized_test_id", "标化主表 ID"),
        Map.entry("is_applicable", "是否适用"),
        Map.entry("not_applicable_reason", "不适用原因"),
        Map.entry("best_test_type", "最佳标化考试类型"),
        Map.entry("best_total_score", "最佳总分"),
        Map.entry("test_type", "考试类型"),
        Map.entry("status", "考试状态"),
        Map.entry("estimated_total_score", "预估总分"),
        Map.entry("sat_erw", "SAT 读写"),
        Map.entry("sat_math", "SAT 数学"),
        Map.entry("act_english", "ACT 英语"),
        Map.entry("act_math", "ACT 数学"),
        Map.entry("act_reading", "ACT 阅读"),
        Map.entry("act_science", "ACT 科学"),
        Map.entry("t1_examples_text", "T1 示例说明"),
        Map.entry("t2_examples_text", "T2 示例说明"),
        Map.entry("t3_examples_text", "T3 示例说明"),
        Map.entry("t4_examples_text", "T4 示例说明"),
        Map.entry("tier_reference_notes", "层级补充说明"),
        Map.entry("sort_order", "排序"),
        Map.entry("competition_name", "竞赛名称"),
        Map.entry("competition_field", "竞赛领域"),
        Map.entry("competition_tier", "竞赛层级"),
        Map.entry("competition_level", "竞赛级别"),
        Map.entry("result_text", "结果描述"),
        Map.entry("rank_value", "名次"),
        Map.entry("participants_count", "参赛人数"),
        Map.entry("percentile", "百分位"),
        Map.entry("competition_year", "年份"),
        Map.entry("evidence_type", "佐证类型"),
        Map.entry("evidence_link_or_note", "佐证链接或备注"),
        Map.entry("prefer_long_term", "是否偏好长期活动"),
        Map.entry("prefer_leadership_roles", "是否偏好领导角色"),
        Map.entry("impact_required_field", "影响力必填字段"),
        Map.entry("quality_rules_notes", "活动质量规则说明"),
        Map.entry("activity_name", "活动名称"),
        Map.entry("activity_category", "活动类别"),
        Map.entry("activity_role", "活动角色"),
        Map.entry("duration_months", "持续月数"),
        Map.entry("weekly_hours", "每周投入小时"),
        Map.entry("team_size", "团队人数"),
        Map.entry("people_reached", "影响人数"),
        Map.entry("events_run", "举办活动数"),
        Map.entry("funds_raised", "筹款金额"),
        Map.entry("awards_or_media", "获奖或媒体报道"),
        Map.entry("output_preferred", "是否偏好有产出"),
        Map.entry("internal_only_output_penalty", "仅内部产出是否扣分"),
        Map.entry("strictness_rules_notes", "项目严格性规则说明"),
        Map.entry("project_id", "项目 ID"),
        Map.entry("project_name", "项目名称"),
        Map.entry("project_type", "项目类型"),
        Map.entry("project_field", "项目领域"),
        Map.entry("relevance_to_major", "与专业相关性"),
        Map.entry("hours_total", "总投入小时"),
        Map.entry("output_type", "产出类型"),
        Map.entry("link_or_note", "链接或备注"),
        Map.entry("notes", "备注")
    );
    public static final Map<String, String> FIELD_HELPERS = Map.ofEntries(
        Map.entry(key("student_basic_info", "MAJ_INTEREST_TEXT"), "如果目标专业下拉里没有合适选项，可在这里填写原始表述，例如：人文。"),
        Map.entry(key("student_competition_entries", "notes"), "可以写介绍一下你参加的比赛和你拿到的名次。")
    );

    public static final Map<String, Set<String>> HIDDEN_FIELDS_BY_TABLE = Map.ofEntries(
        Map.entry("student_basic_info", Set.of("curriculum_system_notes")),
        Map.entry("student_basic_info_curriculum_system", Set.of("notes")),
        Map.entry("student_academic", Set.of("curriculum_combination_notes", "other_curriculum_notes", "rank_evidence_notes", "rank_scope_code", "school_code_val", "school_type_notes")),
        Map.entry("student_academic_a_level_profile", Set.of("notes")),
        Map.entry("student_academic_a_level_subject", Set.of("notes")),
        Map.entry("student_academic_ap_profile", Set.of("ap_count", "best_n_ap_for_scoring", "class_rank_available", "honors_count", "max_ap_offered_by_school", "notes")),
        Map.entry("student_academic_ap_course", Set.of("notes")),
        Map.entry("student_academic_ib_profile", Set.of("notes")),
        Map.entry("student_academic_ib_subject", Set.of("notes")),
        Map.entry("student_academic_chinese_high_school_profile", Set.of("notes")),
        Map.entry("student_academic_chinese_high_school_subject", Set.of("notes")),
        Map.entry("student_academic_other_curriculum_profile", Set.of("curriculum_scope_code", "notes")),
        Map.entry("student_language_ielts", Set.of("estimated_total", "evidence_level_code", "is_best_score", "normalized_index_100")),
        Map.entry("student_language_toefl_ibt", Set.of("estimated_total", "evidence_level_code", "is_best_score", "normalized_index_100")),
        Map.entry("student_language_toefl_essentials", Set.of("estimated_total", "evidence_level_code", "is_best_score", "normalized_index_100")),
        Map.entry("student_language_det", Set.of("estimated_total", "evidence_level_code", "is_best_score", "normalized_index_100")),
        Map.entry("student_language_pte", Set.of("estimated_total", "evidence_level_code", "is_best_score", "normalized_index_100")),
        Map.entry("student_language_languagecert", Set.of("estimated_total", "evidence_level_code", "is_best_score", "normalized_index_100")),
        Map.entry("student_language_cambridge", Set.of("estimated_total", "evidence_level_code", "is_best_score", "normalized_index_100")),
        Map.entry("student_language_other", Set.of("estimated_total", "evidence_level_code", "is_best_score", "normalized_index_100")),
        Map.entry("student_standardized_test_records", Set.of("is_best_score")),
        Map.entry("student_competition_entries", Set.of("competition_tier", "competition_year", "evidence_link_or_note", "evidence_type", "participants_count", "percentile", "rank_value", "result_text", "sort_order")),
        Map.entry("student_activity_entries", Set.of("activity_category", "activity_name", "activity_role", "awards_or_media", "duration_months", "events_run", "evidence_link_or_note", "evidence_type", "funds_raised", "people_reached", "sort_order", "team_size", "weekly_hours")),
        Map.entry("student_project_entries", Set.of("duration_months", "evidence_link_or_note", "evidence_type", "hours_total", "project_field", "project_id", "project_name", "project_type", "relevance_to_major", "sort_order", "team_size"))
    );

    public static final Map<String, List<String>> ENUM_FIELD_OPTIONS = Map.ofEntries(
        Map.entry(key("student_academic", "school_type_code"), List.of("PUBLIC", "PRIVATE", "INTERNATIONAL", "OTHER")),
        Map.entry(key("student_academic", "rank_scope_code"), List.of("GRADE", "CLASS", "TRACK", "SCHOOL", "OTHER")),
        Map.entry(key("student_academic", "rank_evidence_level_code"), List.of("CONFIRMED", "SELF_REPORTED", "ESTIMATED", "TRANSCRIPT", "SCHOOL_SYSTEM", "OTHER")),
        Map.entry(key("student_academic_us_high_school_course", "term_code"), List.of("FALL", "SPRING", "FULL_YEAR", "SUMMER", "OTHER")),
        Map.entry(key("student_academic_us_high_school_course", "course_category_code"), List.of("ENGLISH", "MATH", "SCIENCE", "SOCIAL_SCIENCE", "WORLD_LANGUAGE", "ARTS", "CS", "BUSINESS", "ELECTIVE", "OTHER")),
        Map.entry(key("student_academic_us_high_school_course", "course_level_code"), List.of("REGULAR", "HONORS", "AP", "IB", "DUAL_ENROLLMENT", "ADVANCED", "OTHER")),
        Map.entry(key("student_academic_us_high_school_course", "grade_letter_code"), List.of("A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D", "F", "P", "NP", "W", "NA")),
        Map.entry(key("student_academic_a_level_subject", "stage_code"), List.of("AS", "A2", "FULL_A_LEVEL", "IN_PROGRESS")),
        Map.entry(key("student_academic_a_level_subject", "grade_code"), List.of("A*", "A", "B", "C", "D", "E", "U", "NA")),
        Map.entry(key("student_academic_a_level_subject", "board_code"), List.of("CAIE", "EDEXCEL", "AQA", "OCR", "OTHER", "UNKNOWN")),
        Map.entry(key("student_academic_a_level_subject", "session_code"), List.of("MAY_JUNE", "OCT_NOV", "JAN", "OTHER", "UNKNOWN")),
        Map.entry(key("student_academic_ib_profile", "tok_grade_code"), List.of("A", "B", "C", "D", "E", "NA")),
        Map.entry(key("student_academic_ib_profile", "ee_grade_code"), List.of("A", "B", "C", "D", "E", "NA")),
        Map.entry(key("student_academic_ib_subject", "level_code"), List.of("HL", "SL")),
        Map.entry(key("student_academic_chinese_high_school_profile", "grading_system_code"), List.of("PERCENT_100", "GPA_4", "GPA_5", "OTHER")),
        Map.entry(key("student_language", "best_score_status_code"), List.of("SCORED", "PLANNED", "ESTIMATED")),
        Map.entry(key("student_language", "overall_cefr_level_code"), List.of("A1", "A2", "B1", "B2", "C1", "C2", "UNKNOWN")),
        Map.entry(key("student_language_ielts", "status_code"), List.of("SCORED", "PLANNED", "ESTIMATED")),
        Map.entry(key("student_language_toefl_ibt", "status_code"), List.of("SCORED", "PLANNED", "ESTIMATED")),
        Map.entry(key("student_language_toefl_essentials", "status_code"), List.of("SCORED", "PLANNED", "ESTIMATED")),
        Map.entry(key("student_language_det", "status_code"), List.of("SCORED", "PLANNED", "ESTIMATED")),
        Map.entry(key("student_language_pte", "status_code"), List.of("SCORED", "PLANNED", "ESTIMATED")),
        Map.entry(key("student_language_languagecert", "status_code"), List.of("SCORED", "PLANNED", "ESTIMATED")),
        Map.entry(key("student_language_cambridge", "status_code"), List.of("SCORED", "PLANNED", "ESTIMATED")),
        Map.entry(key("student_language_other", "status_code"), List.of("SCORED", "PLANNED", "ESTIMATED")),
        Map.entry(key("student_language_ielts", "evidence_level_code"), List.of("CONFIRMED", "SELF_REPORTED", "ESTIMATED")),
        Map.entry(key("student_language_toefl_ibt", "evidence_level_code"), List.of("CONFIRMED", "SELF_REPORTED", "ESTIMATED")),
        Map.entry(key("student_language_toefl_essentials", "evidence_level_code"), List.of("CONFIRMED", "SELF_REPORTED", "ESTIMATED")),
        Map.entry(key("student_language_det", "evidence_level_code"), List.of("CONFIRMED", "SELF_REPORTED", "ESTIMATED")),
        Map.entry(key("student_language_pte", "evidence_level_code"), List.of("CONFIRMED", "SELF_REPORTED", "ESTIMATED")),
        Map.entry(key("student_language_languagecert", "evidence_level_code"), List.of("CONFIRMED", "SELF_REPORTED", "ESTIMATED")),
        Map.entry(key("student_language_cambridge", "evidence_level_code"), List.of("CONFIRMED", "SELF_REPORTED", "ESTIMATED")),
        Map.entry(key("student_language_other", "evidence_level_code"), List.of("CONFIRMED", "SELF_REPORTED", "ESTIMATED")),
        Map.entry(key("student_language_languagecert", "cefr_level_code"), List.of("A1", "A2", "B1", "B2", "C1", "C2", "UNKNOWN")),
        Map.entry(key("student_language_cambridge", "cefr_level_code"), List.of("A1", "A2", "B1", "B2", "C1", "C2", "UNKNOWN")),
        Map.entry(key("student_language_other", "cefr_level_code"), List.of("A1", "A2", "B1", "B2", "C1", "C2", "UNKNOWN")),
        Map.entry(key("student_standardized_tests", "best_test_type"), List.of("SAT", "ACT")),
        Map.entry(key("student_standardized_test_records", "test_type"), List.of("SAT", "ACT")),
        Map.entry(key("student_standardized_test_records", "status"), List.of("SCORED", "PLANNED", "ESTIMATED")),
        Map.entry(key("student_competition_entries", "competition_field"), List.of("MATH", "CS", "PHYSICS", "CHEM", "BIO", "ECON", "DEBATE", "WRITING", "OTHER")),
        Map.entry(key("student_competition_entries", "competition_tier"), List.of("T1", "T2", "T3", "T4", "UNKNOWN")),
        Map.entry(key("student_competition_entries", "competition_level"), List.of("SCHOOL", "CITY", "PROVINCE", "NATIONAL", "INTERNATIONAL")),
        Map.entry(key("student_competition_entries", "evidence_type"), List.of("CERTIFICATE", "LINK", "SCHOOL_CONFIRMATION", "NONE")),
        Map.entry(key("student_activity_entries", "activity_category"), List.of("LEADERSHIP", "ACADEMIC", "SPORTS", "ARTS", "COMMUNITY", "ENTREPRENEURSHIP", "OTHER")),
        Map.entry(key("student_activity_entries", "activity_role"), List.of("FOUNDER", "PRESIDENT", "CORE_MEMBER", "MEMBER", "OTHER")),
        Map.entry(key("student_activity_entries", "evidence_type"), List.of("LINK", "SCHOOL_CONFIRMATION", "PHOTO", "NONE")),
        Map.entry(key("student_project_entries", "project_type"), List.of("RESEARCH", "INTERNSHIP", "ENGINEERING_PROJECT", "STARTUP", "CREATIVE_PROJECT", "VOLUNTEER_WORK", "OTHER")),
        Map.entry(key("student_project_entries", "project_field"), List.of("CS", "ECON", "FIN", "BIO", "PHYS", "DESIGN", "OTHER")),
        Map.entry(key("student_project_entries", "relevance_to_major"), List.of("HIGH", "MEDIUM", "LOW")),
        Map.entry(key("student_project_entries", "evidence_type"), List.of("LINK", "MENTOR_LETTER", "EMPLOYER_CONFIRMATION", "NONE")),
        Map.entry(key("student_project_outputs", "output_type"), List.of("PAPER", "REPORT", "CODE", "DEMO", "PRODUCT", "PORTFOLIO", "PRESENTATION", "OTHER"))
    );
    public static final Map<String, Map<String, String>> ENUM_OPTION_LABELS = Map.ofEntries(
        Map.entry(key("student_academic", "school_type_code"), Map.ofEntries(Map.entry("PUBLIC", "公立学校"), Map.entry("PRIVATE", "私立学校"), Map.entry("INTERNATIONAL", "国际学校"), Map.entry("OTHER", "其他"))),
        Map.entry(key("student_academic", "rank_scope_code"), Map.ofEntries(Map.entry("GRADE", "年级"), Map.entry("CLASS", "班级"), Map.entry("TRACK", "课程轨道"), Map.entry("SCHOOL", "全校"), Map.entry("OTHER", "其他"))),
        Map.entry(key("student_academic", "rank_evidence_level_code"), Map.ofEntries(Map.entry("CONFIRMED", "已确认"), Map.entry("SELF_REPORTED", "学生自述"), Map.entry("ESTIMATED", "估算"), Map.entry("TRANSCRIPT", "成绩单"), Map.entry("SCHOOL_SYSTEM", "学校系统"), Map.entry("OTHER", "其他"))),
        Map.entry(key("student_academic_us_high_school_course", "term_code"), Map.ofEntries(Map.entry("FALL", "秋季学期"), Map.entry("SPRING", "春季学期"), Map.entry("FULL_YEAR", "全年课"), Map.entry("SUMMER", "暑期"), Map.entry("OTHER", "其他"))),
        Map.entry(key("student_academic_us_high_school_course", "course_category_code"), Map.ofEntries(Map.entry("ENGLISH", "英语"), Map.entry("MATH", "数学"), Map.entry("SCIENCE", "科学"), Map.entry("SOCIAL_SCIENCE", "社会科学"), Map.entry("WORLD_LANGUAGE", "外语"), Map.entry("ARTS", "艺术"), Map.entry("CS", "计算机"), Map.entry("BUSINESS", "商科"), Map.entry("ELECTIVE", "选修"), Map.entry("OTHER", "其他"))),
        Map.entry(key("student_academic_us_high_school_course", "course_level_code"), Map.ofEntries(Map.entry("REGULAR", "Regular"), Map.entry("HONORS", "Honors"), Map.entry("AP", "AP"), Map.entry("IB", "IB"), Map.entry("DUAL_ENROLLMENT", "Dual Enrollment"), Map.entry("ADVANCED", "Advanced"), Map.entry("OTHER", "其他"))),
        Map.entry(key("student_academic_us_high_school_course", "grade_letter_code"), Map.ofEntries(Map.entry("A+", "A+"), Map.entry("A", "A"), Map.entry("A-", "A-"), Map.entry("B+", "B+"), Map.entry("B", "B"), Map.entry("B-", "B-"), Map.entry("C+", "C+"), Map.entry("C", "C"), Map.entry("C-", "C-"), Map.entry("D", "D"), Map.entry("F", "F"), Map.entry("P", "Pass"), Map.entry("NP", "No Pass"), Map.entry("W", "Withdraw"), Map.entry("NA", "暂未评级"))),
        Map.entry(key("student_academic_a_level_subject", "stage_code"), Map.ofEntries(Map.entry("AS", "AS 阶段"), Map.entry("A2", "A2 阶段"), Map.entry("FULL_A_LEVEL", "完整 A-Level"), Map.entry("IN_PROGRESS", "修读中"))),
        Map.entry(key("student_academic_a_level_subject", "grade_code"), Map.ofEntries(Map.entry("A*", "A*"), Map.entry("A", "A"), Map.entry("B", "B"), Map.entry("C", "C"), Map.entry("D", "D"), Map.entry("E", "E"), Map.entry("U", "U"), Map.entry("NA", "暂未评级"))),
        Map.entry(key("student_academic_a_level_subject", "board_code"), Map.ofEntries(Map.entry("CAIE", "剑桥国际"), Map.entry("EDEXCEL", "爱德思"), Map.entry("AQA", "AQA"), Map.entry("OCR", "OCR"), Map.entry("OTHER", "其他"), Map.entry("UNKNOWN", "未知"))),
        Map.entry(key("student_academic_a_level_subject", "session_code"), Map.ofEntries(Map.entry("MAY_JUNE", "5-6 月"), Map.entry("OCT_NOV", "10-11 月"), Map.entry("JAN", "1 月"), Map.entry("OTHER", "其他"), Map.entry("UNKNOWN", "未知"))),
        Map.entry(key("student_academic_ib_subject", "level_code"), Map.ofEntries(Map.entry("HL", "HL 高阶"), Map.entry("SL", "SL 标准级"))),
        Map.entry(key("student_academic_ib_profile", "tok_grade_code"), Map.ofEntries(Map.entry("A", "A 等"), Map.entry("B", "B 等"), Map.entry("C", "C 等"), Map.entry("D", "D 等"), Map.entry("E", "E 等"), Map.entry("NA", "暂未评级"))),
        Map.entry(key("student_academic_ib_profile", "ee_grade_code"), Map.ofEntries(Map.entry("A", "A 等"), Map.entry("B", "B 等"), Map.entry("C", "C 等"), Map.entry("D", "D 等"), Map.entry("E", "E 等"), Map.entry("NA", "暂未评级"))),
        Map.entry(key("student_academic_chinese_high_school_profile", "grading_system_code"), Map.ofEntries(Map.entry("PERCENT_100", "百分制"), Map.entry("GPA_4", "4 分制 GPA"), Map.entry("GPA_5", "5 分制 GPA"), Map.entry("OTHER", "其他"))),
        Map.entry(key("student_language", "best_score_status_code"), Map.ofEntries(Map.entry("SCORED", "已出分"), Map.entry("PLANNED", "计划参加"), Map.entry("ESTIMATED", "预估"))),
        Map.entry(key("student_language", "overall_cefr_level_code"), Map.ofEntries(Map.entry("A1", "入门级"), Map.entry("A2", "初级"), Map.entry("B1", "中级"), Map.entry("B2", "中高级"), Map.entry("C1", "高级"), Map.entry("C2", "精通级"), Map.entry("UNKNOWN", "未知"))),
        Map.entry(key("student_language_ielts", "status_code"), Map.ofEntries(Map.entry("SCORED", "已出分"), Map.entry("PLANNED", "计划参加"), Map.entry("ESTIMATED", "预估"))),
        Map.entry(key("student_language_toefl_ibt", "status_code"), Map.ofEntries(Map.entry("SCORED", "已出分"), Map.entry("PLANNED", "计划参加"), Map.entry("ESTIMATED", "预估"))),
        Map.entry(key("student_language_toefl_essentials", "status_code"), Map.ofEntries(Map.entry("SCORED", "已出分"), Map.entry("PLANNED", "计划参加"), Map.entry("ESTIMATED", "预估"))),
        Map.entry(key("student_language_det", "status_code"), Map.ofEntries(Map.entry("SCORED", "已出分"), Map.entry("PLANNED", "计划参加"), Map.entry("ESTIMATED", "预估"))),
        Map.entry(key("student_language_pte", "status_code"), Map.ofEntries(Map.entry("SCORED", "已出分"), Map.entry("PLANNED", "计划参加"), Map.entry("ESTIMATED", "预估"))),
        Map.entry(key("student_language_languagecert", "status_code"), Map.ofEntries(Map.entry("SCORED", "已出分"), Map.entry("PLANNED", "计划参加"), Map.entry("ESTIMATED", "预估"))),
        Map.entry(key("student_language_cambridge", "status_code"), Map.ofEntries(Map.entry("SCORED", "已出分"), Map.entry("PLANNED", "计划参加"), Map.entry("ESTIMATED", "预估"))),
        Map.entry(key("student_language_other", "status_code"), Map.ofEntries(Map.entry("SCORED", "已出分"), Map.entry("PLANNED", "计划参加"), Map.entry("ESTIMATED", "预估"))),
        Map.entry(key("student_language_ielts", "evidence_level_code"), Map.ofEntries(Map.entry("CONFIRMED", "已确认"), Map.entry("SELF_REPORTED", "学生自述"), Map.entry("ESTIMATED", "预估"))),
        Map.entry(key("student_language_toefl_ibt", "evidence_level_code"), Map.ofEntries(Map.entry("CONFIRMED", "已确认"), Map.entry("SELF_REPORTED", "学生自述"), Map.entry("ESTIMATED", "预估"))),
        Map.entry(key("student_language_toefl_essentials", "evidence_level_code"), Map.ofEntries(Map.entry("CONFIRMED", "已确认"), Map.entry("SELF_REPORTED", "学生自述"), Map.entry("ESTIMATED", "预估"))),
        Map.entry(key("student_language_det", "evidence_level_code"), Map.ofEntries(Map.entry("CONFIRMED", "已确认"), Map.entry("SELF_REPORTED", "学生自述"), Map.entry("ESTIMATED", "预估"))),
        Map.entry(key("student_language_pte", "evidence_level_code"), Map.ofEntries(Map.entry("CONFIRMED", "已确认"), Map.entry("SELF_REPORTED", "学生自述"), Map.entry("ESTIMATED", "预估"))),
        Map.entry(key("student_language_languagecert", "evidence_level_code"), Map.ofEntries(Map.entry("CONFIRMED", "已确认"), Map.entry("SELF_REPORTED", "学生自述"), Map.entry("ESTIMATED", "预估"))),
        Map.entry(key("student_language_cambridge", "evidence_level_code"), Map.ofEntries(Map.entry("CONFIRMED", "已确认"), Map.entry("SELF_REPORTED", "学生自述"), Map.entry("ESTIMATED", "预估"))),
        Map.entry(key("student_language_other", "evidence_level_code"), Map.ofEntries(Map.entry("CONFIRMED", "已确认"), Map.entry("SELF_REPORTED", "学生自述"), Map.entry("ESTIMATED", "预估"))),
        Map.entry(key("student_language_languagecert", "cefr_level_code"), Map.ofEntries(Map.entry("A1", "入门级"), Map.entry("A2", "初级"), Map.entry("B1", "中级"), Map.entry("B2", "中高级"), Map.entry("C1", "高级"), Map.entry("C2", "精通级"), Map.entry("UNKNOWN", "未知"))),
        Map.entry(key("student_language_cambridge", "cefr_level_code"), Map.ofEntries(Map.entry("A1", "入门级"), Map.entry("A2", "初级"), Map.entry("B1", "中级"), Map.entry("B2", "中高级"), Map.entry("C1", "高级"), Map.entry("C2", "精通级"), Map.entry("UNKNOWN", "未知"))),
        Map.entry(key("student_language_other", "cefr_level_code"), Map.ofEntries(Map.entry("A1", "入门级"), Map.entry("A2", "初级"), Map.entry("B1", "中级"), Map.entry("B2", "中高级"), Map.entry("C1", "高级"), Map.entry("C2", "精通级"), Map.entry("UNKNOWN", "未知"))),
        Map.entry(key("student_standardized_tests", "best_test_type"), Map.ofEntries(Map.entry("SAT", "SAT"), Map.entry("ACT", "ACT"))),
        Map.entry(key("student_standardized_test_records", "test_type"), Map.ofEntries(Map.entry("SAT", "SAT"), Map.entry("ACT", "ACT"))),
        Map.entry(key("student_standardized_test_records", "status"), Map.ofEntries(Map.entry("SCORED", "已出分"), Map.entry("PLANNED", "计划参加"), Map.entry("ESTIMATED", "预估"))),
        Map.entry(key("student_competition_entries", "competition_field"), Map.ofEntries(Map.entry("MATH", "数学"), Map.entry("CS", "计算机"), Map.entry("PHYSICS", "物理"), Map.entry("CHEM", "化学"), Map.entry("BIO", "生物"), Map.entry("ECON", "经济"), Map.entry("DEBATE", "辩论"), Map.entry("WRITING", "写作"), Map.entry("OTHER", "其他"))),
        Map.entry(key("student_competition_entries", "competition_tier"), Map.ofEntries(Map.entry("T1", "第一梯队"), Map.entry("T2", "第二梯队"), Map.entry("T3", "第三梯队"), Map.entry("T4", "第四梯队"), Map.entry("UNKNOWN", "未知"))),
        Map.entry(key("student_competition_entries", "competition_level"), Map.ofEntries(Map.entry("SCHOOL", "校级"), Map.entry("CITY", "市级"), Map.entry("PROVINCE", "省级"), Map.entry("NATIONAL", "国家级"), Map.entry("INTERNATIONAL", "国际级"))),
        Map.entry(key("student_competition_entries", "evidence_type"), Map.ofEntries(Map.entry("CERTIFICATE", "证书"), Map.entry("LINK", "链接"), Map.entry("SCHOOL_CONFIRMATION", "学校证明"), Map.entry("NONE", "无"))),
        Map.entry(key("student_activity_entries", "activity_category"), Map.ofEntries(Map.entry("LEADERSHIP", "领导力活动"), Map.entry("ACADEMIC", "学术活动"), Map.entry("SPORTS", "体育活动"), Map.entry("ARTS", "艺术活动"), Map.entry("COMMUNITY", "社区活动"), Map.entry("ENTREPRENEURSHIP", "创业活动"), Map.entry("OTHER", "其他"))),
        Map.entry(key("student_activity_entries", "activity_role"), Map.ofEntries(Map.entry("FOUNDER", "创始人"), Map.entry("PRESIDENT", "负责人"), Map.entry("CORE_MEMBER", "核心成员"), Map.entry("MEMBER", "成员"), Map.entry("OTHER", "其他"))),
        Map.entry(key("student_activity_entries", "evidence_type"), Map.ofEntries(Map.entry("LINK", "链接"), Map.entry("SCHOOL_CONFIRMATION", "学校证明"), Map.entry("PHOTO", "照片"), Map.entry("NONE", "无"))),
        Map.entry(key("student_project_entries", "project_type"), Map.ofEntries(Map.entry("RESEARCH", "科研项目"), Map.entry("INTERNSHIP", "实习经历"), Map.entry("ENGINEERING_PROJECT", "工程项目"), Map.entry("STARTUP", "创业项目"), Map.entry("CREATIVE_PROJECT", "创意项目"), Map.entry("VOLUNTEER_WORK", "志愿工作"), Map.entry("OTHER", "其他"))),
        Map.entry(key("student_project_entries", "project_field"), Map.ofEntries(Map.entry("CS", "计算机"), Map.entry("ECON", "经济"), Map.entry("FIN", "金融"), Map.entry("BIO", "生物"), Map.entry("PHYS", "物理"), Map.entry("DESIGN", "设计"), Map.entry("OTHER", "其他"))),
        Map.entry(key("student_project_entries", "relevance_to_major"), Map.ofEntries(Map.entry("HIGH", "高相关"), Map.entry("MEDIUM", "中相关"), Map.entry("LOW", "低相关"))),
        Map.entry(key("student_project_entries", "evidence_type"), Map.ofEntries(Map.entry("LINK", "链接"), Map.entry("MENTOR_LETTER", "导师证明"), Map.entry("EMPLOYER_CONFIRMATION", "单位证明"), Map.entry("NONE", "无"))),
        Map.entry(key("student_project_outputs", "output_type"), Map.ofEntries(Map.entry("PAPER", "论文"), Map.entry("REPORT", "报告"), Map.entry("CODE", "代码"), Map.entry("DEMO", "演示"), Map.entry("PRODUCT", "产品"), Map.entry("PORTFOLIO", "作品集"), Map.entry("PRESENTATION", "展示材料"), Map.entry("OTHER", "其他")))
    );

    public static final List<Map<String, String>> CURRENT_GRADE_OPTIONS = List.of(
        option("初一", "初一"),
        option("初二", "初二"),
        option("初三", "初三"),
        option("高一", "高一"),
        option("高二", "高二"),
        option("高三", "高三"),
        option("G9", "G9 (初三)"),
        option("G10", "G10 (高一)"),
        option("G11", "G11 (高二)"),
        option("G12", "G12 (高三)"),
        option("大一", "大一"),
        option("大二", "大二"),
        option("大三", "大三"),
        option("大四", "大四"),
        option("Gap Year", "Gap Year"),
        option("TRANSFER_YEAR_1", "大一转学申请"),
        option("已毕业", "已毕业"),
        option("OTHER", "其他")
    );

    public static final List<Map<String, String>> SCHOOL_CITY_OPTIONS = buildStaticOptions(List.of(
        "北京", "上海", "广州", "深圳", "杭州", "南京",
        "苏州", "成都", "重庆", "武汉", "西安", "天津", "青岛",
        "宁波", "长沙", "郑州", "合肥", "厦门", "福州", "南昌",
        "昆明", "海口", "香港", "澳门", "台北", "新加坡", "伦敦",
        "曼彻斯特", "爱丁堡", "纽约", "波士顿", "洛杉矶", "芝加哥",
        "多伦多", "温哥华", "墨尔本", "悉尼", "其他"
    ));

    private BusinessProfileFormMetadata() {
    }

    private static List<Map<String, String>> buildStaticOptions(List<String> values) {
        return values.stream().map(value -> option(value, value)).toList();
    }

    private static Map<String, String> option(String value, String label) {
        Map<String, String> result = new LinkedHashMap<>();
        result.put("value", value);
        result.put("label", label);
        return result;
    }

    private static String key(String tableName, String fieldName) {
        return tableName + "." + fieldName;
    }
}
